openapi: 3.0.3
info:
  title: example spec
  description: 'an example openapi spec'
  version: 0.1.0
paths:
  /api/example:
    get:
      summary: An example
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: string
