name: Build and Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v3

      - run: yarn run ci:lint
      - run: yarn run ci:test
      - run: yarn run ci:build
