name: example-run
on:
  pull_request:

jobs:
  optic-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run optic compare
        uses: ./
        with:
          token: ${{ secrets.OPTIC_TOKEN }}
